Repository open-ani/animeko, pull requests merged in 2025-01, with the labels that each got.

#1416 为桌面端添加水平滚动列表的按钮
  app/shared/app-data/src/commonMain/kotlin/data/models/preference/OneshotActionConfig.kt
  app/shared/src/androidMain/kotlin/ui/exploration/ExplorationPage.android.kt
  app/shared/src/commonMain/kotlin/ui/main/ExplorationPageViewModel.kt
  app/shared/src/desktopTest/kotlin/ui/foundation/HorizontalScrollControlScaffoldTest.kt
  app/shared/ui-adaptive/src/commonMain/kotlin/ui/adaptive/HorizontalScrollControlScaffoldOnDesktop.kt
  app/shared/ui-exploration/src/commonMain/kotlin/ui/exploration/ExplorationPage.kt
  app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/HorizontalScrollControlScaffold.kt
Labels: s: ui

#1369 为发评论增加 Turnstile 支持
  app/shared/app-data/src/commonMain/kotlin/data/network/BangumiCommentService.kt
  app/shared/app-data/src/commonMain/kotlin/data/repository/episode/BangumiCommentRepository.kt
  app/shared/src/androidMain/kotlin/ui/subject/episode/comments/EditCommentSheet.android.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodePage.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/comments/EpisodeCommentColumn.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/comments/EpisodeEditCommentSheet.kt
  app/shared/ui-comment/src/androidMain/kotlin/ui/comment/Turnstile.android.kt
  app/shared/ui-comment/src/commonMain/kotlin/ui/comment/CommentColumn.kt
  app/shared/ui-comment/src/commonMain/kotlin/ui/comment/CommentEditorState.kt
  app/shared/ui-comment/src/commonMain/kotlin/ui/comment/EditComment.kt
  app/shared/ui-comment/src/commonMain/kotlin/ui/comment/Turnstile.kt
  app/shared/ui-comment/src/desktopMain/kotlin/package.kt
  app/shared/ui-comment/src/desktopMain/kotlin/ui/comment/Turnstile.desktop.kt
  app/shared/ui-comment/src/iosMain/kotlin/package.kt
  app/shared/ui-comment/src/iosMain/kotlin/ui/comment/Turnstile.ios.kt
  app/shared/ui-subject/src/commonMain/kotlin/ui/subject/details/SubjectDetailsPage.kt
  app/shared/ui-subject/src/commonMain/kotlin/ui/subject/details/components/SubjectCommentColumn.kt
  app/shared/ui-subject/src/commonMain/kotlin/ui/subject/details/state/SubjectDetailsState.kt
Labels: s: comment

#1445 CollectionPage Badges and SubjectDetailPage TabRow
  CONTRIBUTING.md
  README.md
  app/shared/ui-subject/src/commonMain/kotlin/ui/subject/collection/CollectionPage.kt
  app/shared/ui-subject/src/commonMain/kotlin/ui/subject/details/SubjectDetailsPage.kt
  app/shared/ui-subject/src/commonMain/kotlin/ui/subject/details/components/DetailsTab.kt
Labels: s: ui

#1480 Use Retry@v3
  .github/workflows/src.main.kts
Labels: s: build

#1477 Update anitorrent to 0.1.1
  settings.gradle.kts
Labels: s: torrent

#1523 Use JBR b750.29 on Windows
  .github/workflows/build.yml
  .github/workflows/download_jbr.py
  .github/workflows/release.yml
  .github/workflows/src.main.kts
Labels: s: build

#1587 Refactor MediaSourceResultListPresentation to be stateless
  app/shared/app-data/src/commonMain/kotlin/domain/media/fetch/FilteredMediaSourceResults.kt
  app/shared/app-data/src/commonMain/kotlin/domain/media/fetch/MediaFetchSession.kt
  app/shared/app-data/src/commonMain/kotlin/domain/media/fetch/MediaSourceResultsFilterer.kt
  app/shared/src/androidMain/kotlin/ui/subject/episode/EpisodeVideo.android.kt
  app/shared/src/androidMain/kotlin/ui/subject/episode/details/EpisodeDetails.android.kt
  app/shared/src/androidMain/kotlin/ui/subject/episode/details/EpisodePlayMediaSelectorSheet.android.kt
  app/shared/src/androidMain/kotlin/ui/subject/episode/mediaFetch/MediaSelector.android.kt
  app/shared/src/androidMain/kotlin/ui/subject/episode/video/sidesheet/EpisodeVideoMediaSelectorSideSheet.android.kt
  app/shared/src/commonMain/kotlin/ui/subject/cache/CacheListGroup.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodePage.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/details/EpisodeDetails.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/details/EpisodePlayMediaSelector.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/mediaFetch/MediaSourceResultPresentation.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/mediaFetch/MediaSourceResultsView.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EpisodeVideoMediaSelectorSideSheet.kt
  app/shared/src/desktopTest/kotlin/ui/subject/episode/EpisodeVideoControllerTest.kt
Labels: s: ui

#1558 Compose 1.8
  app/shared/src/commonMain/kotlin/ui/main/MainScene.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodePage.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/mediaFetch/MediaSelectorFilters.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/mediaFetch/MediaSourceResultsView.kt
  app/shared/src/commonTest/kotlin/ui/framework/AniComposeUiTest.kt
  app/shared/src/desktopTest/kotlin/ui/subject/episode/EpisodeVideoControllerTest.kt
  app/shared/ui-adaptive/src/commonMain/kotlin/ui/adaptive/AdaptiveSearchBar.kt
  app/shared/ui-adaptive/src/commonMain/kotlin/ui/adaptive/AniListDetailPaneScaffold.kt
  app/shared/ui-adaptive/src/commonMain/kotlin/ui/adaptive/AniTopAppBar.kt
  app/shared/ui-adaptive/src/commonMain/kotlin/ui/adaptive/navigation/AniNavigationSuiteScaffold.kt
  app/shared/ui-adaptive/src/commonMain/kotlin/ui/adaptive/navigation/NavigationSuite.kt
  app/shared/ui-exploration/src/commonMain/kotlin/ui/exploration/ExplorationPage.kt
  app/shared/ui-exploration/src/commonMain/kotlin/ui/exploration/followed/FollowedSubjectsLazyRow.kt
  app/shared/ui-exploration/src/commonMain/kotlin/ui/exploration/schedule/SchedulePage.kt
  app/shared/ui-exploration/src/commonMain/kotlin/ui/exploration/search/SearchPage.kt
  app/shared/ui-exploration/src/commonMain/kotlin/ui/exploration/search/SubjectItem.kt
  app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/layout/CarouselItem.kt
  app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/layout/ListDetailAnimatedPane.kt
  app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/layout/MaterialWindowMarginPaddings.kt
  app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/layout/WindowSizeClasses.kt
  app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/theme/AppTheme.kt
  app/shared/ui-foundation/src/desktopMain/kotlin/ui/foundation/layout/WindowAdaptiveInfo.desktop.kt
  app/shared/ui-settings/src/androidMain/kotlin/ui/settings/tabs/media/source/EditRssMediaSource.android.kt
  app/shared/ui-settings/src/commonMain/kotlin/ui/settings/SettingsPage.kt
  app/shared/ui-settings/src/commonMain/kotlin/ui/settings/framework/components/SettingsScope.kt
  app/shared/ui-settings/src/commonMain/kotlin/ui/settings/mediasource/EditMediaSourceTestDataCardDefaults.kt
  app/shared/ui-settings/src/commonMain/kotlin/ui/settings/mediasource/rss/EditRssMediaSource.kt
  app/shared/ui-settings/src/commonMain/kotlin/ui/settings/mediasource/rss/edit/MediaSourceHeadline.kt
  app/shared/ui-settings/src/commonMain/kotlin/ui/settings/mediasource/selector/EditSelectorMediaSourcePage.kt
  app/shared/ui-settings/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/PeerFilterSettings.kt
  app/shared/ui-subject/src/androidMain/kotlin/ui/subject/collection/SubjectCollectionAction.android.kt
  app/shared/ui-subject/src/commonMain/kotlin/ui/subject/collection/CollectionPage.kt
  app/shared/ui-subject/src/commonMain/kotlin/ui/subject/collection/SubjectCollectionsColumn.kt
  app/shared/ui-subject/src/commonMain/kotlin/ui/subject/collection/components/EditableSubjectCollectionTypeButton.kt
  app/shared/ui-subject/src/commonMain/kotlin/ui/subject/collection/components/SubjectCollectionTypeButton.kt
  app/shared/video-player/src/commonMain/kotlin/ui/guesture/PlayerGestureHost.kt
  danmaku/ui/src/androidMain/kotlin/DanmakuHost.android.kt
  gradle/libs.versions.toml
Labels: z: ready-to-merge

#1584 Fix #1581 新番在自动切换下一集时没有检查是否已播出
  app/shared/app-data/src/commonMain/kotlin/data/models/episode/EpisodeInfo.kt
  app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
Labels: z: ready-to-merge

#1589 重新编写 CONTRIBUTING 文档
  .readme/images/contributing/formatting.png
  CONTRIBUTING.md
  README.md
  docs/contributing/README.md
  docs/contributing/architecture.md
  docs/contributing/building.md
  docs/contributing/code-style.md
  docs/contributing/dev-tips.md
  docs/contributing/images/app-arch-file-tree.png
  docs/contributing/images/edit-run-configuration.png
  docs/contributing/images/find-existing-previews.png
  docs/contributing/images/formatting.png
  docs/contributing/images/idea-settings-download-jdk-version.png
  docs/contributing/images/idea-settings-download-jdk.png
  docs/contributing/images/previewing-compose-ui.png
  docs/contributing/images/run-configuration.png
  docs/contributing/kmp.md
  docs/contributing/setup.md
  docs/contributing/testing.md
Labels: t: documentation

#1590 Redesign navigation transition animation under M3
  app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/layout/ListDetailAnimatedPane.kt
  app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/theme/AppTheme.kt
Labels: s: ui

#1613 Disable Ubuntu CI
  .github/workflows/build.yml
  .github/workflows/src.main.kts
Labels: s: build
